# Site settings
title: Constructores CA
email: hola@constructoresca.com
description: >
  Constructores CA
baseurl: ""
url: "https://constructoresca.com"

twitter_username:
github_username:

# Build settings
markdown: kramdown
