# Site settings
title: Constructores CA
email: hola@constructoresca.com
description: >
  Constructores CA
baseurl: ""
url: "https://constructoresca.com"

twitter_username: constructoresca
instagram_username: constructoresca

# Build settings
markdown: kramdown
